"""add current_identity to users

Revision ID: 329d0ca11757
Revises: 514a5f22a754
Create Date: 2026-04-22 16:50:44.547399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329d0ca11757'
down_revision: Union[str, Sequence[str], None] = '514a5f22a754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_identity', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_identity')
    # ### end Alembic commands ###
