"""add_kb_ids_to_semantic_cache

Revision ID: 95f879bb63ba
Revises: 9881eb1b28f5
Create Date: 2026-05-27 10:10:42.639603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f879bb63ba'
down_revision: Union[str, Sequence[str], None] = '9881eb1b28f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semantic_query_caches', sa.Column('knowledge_base_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semantic_query_caches', 'knowledge_base_ids')
    # ### end Alembic commands ###
