"""create_semantic_cache_table

Revision ID: 9881eb1b28f5
Revises: cd3de51f33a7
Create Date: 2026-05-27 09:56:17.773043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '9881eb1b28f5'
down_revision: Union[str, Sequence[str], None] = 'cd3de51f33a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_query_caches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('query_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('response_events', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_query_caches_id'), 'semantic_query_caches', ['id'], unique=False)
    op.create_index(op.f('ix_semantic_query_caches_question'), 'semantic_query_caches', ['question'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semantic_query_caches_question'), table_name='semantic_query_caches')
    op.drop_index(op.f('ix_semantic_query_caches_id'), table_name='semantic_query_caches')
    op.drop_table('semantic_query_caches')
    # ### end Alembic commands ###
