"""create password_reset_tokens table

Revision ID: 99a14b3be694
Revises: af2b5fa7ff54
Create Date: 2026-04-23 16:33:14.899214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a14b3be694'
down_revision: Union[str, Sequence[str], None] = 'af2b5fa7ff54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
