"""add current_identity to users

Revision ID: cd3de51f33a7
Revises: 0d308e6af591
Create Date: 2026-05-18 15:11:15.000737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3de51f33a7'
down_revision: Union[str, Sequence[str], None] = '0d308e6af591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_content_trgm'), table_name='document_chunks', postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_chunks_content_trgm'), 'document_chunks', ['content'], unique=False, postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
